local map = vim.keymap.set

map({ 'n', 'i', 'x', 's' }, '<C-s>', '<cmd>silent! write<cr><esc>', { desc = 'Save file' })
map('i', 'jk', '<Esc>', { desc = 'Exit insert mode' })
map('n', '<Esc>', '<cmd>nohlsearch<cr>', { desc = 'Clear search highlight' })
map('n', '<leader>q', '<cmd>quit<cr>', { desc = 'Quit window' })
map('n', '<leader>Q', '<cmd>quitall!<cr>', { desc = 'Force quit all' })

map('n', '<C-h>', '<C-w>h', { desc = 'Focus left window' })
map('n', '<C-l>', '<C-w>l', { desc = 'Focus right window' })
map('n', '<leader>wj', '<C-w>j', { desc = 'Focus lower window' })
map('n', '<leader>wk', '<C-w>k', { desc = 'Focus upper window' })
map('n', '<leader>wv', '<cmd>vsplit<cr>', { desc = 'Vertical split' })
map('n', '<leader>wh', '<cmd>split<cr>', { desc = 'Horizontal split' })
map('n', '<leader>wq', '<cmd>close<cr>', { desc = 'Close window' })
map('n', '<leader>wo', '<cmd>only<cr>', { desc = 'Only window' })

map('n', ']b', '<cmd>bnext<cr>', { desc = 'Next buffer' })
map('n', '[b', '<cmd>bprevious<cr>', { desc = 'Previous buffer' })
map('n', '<leader>bb', '<cmd>buffer #<cr>', { desc = 'Alternate buffer' })
map('n', '<leader>bn', '<cmd>enew<cr>', { desc = 'New buffer' })
map('n', '<leader>bd', function()
  local ok, snacks = pcall(require, 'snacks')
  if ok then
    snacks.bufdelete()
  else
    vim.cmd.bdelete()
  end
end, { desc = 'Delete buffer' })

map('n', '<A-j>', '<cmd>move .+1<cr>==', { desc = 'Move line down' })
map('n', '<A-k>', '<cmd>move .-2<cr>==', { desc = 'Move line up' })
map('x', '<A-j>', ":move '>+1<cr>gv=gv", { desc = 'Move selection down' })
map('x', '<A-k>', ":move '<-2<cr>gv=gv", { desc = 'Move selection up' })
map('x', '<', '<gv', { desc = 'Indent left' })
map('x', '>', '>gv', { desc = 'Indent right' })
map('x', 'p', '"_dP', { desc = 'Paste without yanking' })
map({ 'n', 'x' }, '<leader>d', '"_d', { desc = 'Delete without yanking' })
map('n', '<C-a>', 'ggVG', { desc = 'Select all' })

map('n', '<C-d>', '<C-d>zz')
map('n', '<C-u>', '<C-u>zz')
map('n', 'H', '0', { desc = 'Start of line' })
map('n', 'L', '$', { desc = 'End of line' })
map('n', '<C-j>', '5jzz', { desc = 'Down 5 lines' })
map('n', '<C-k>', '5kzz', { desc = 'Up 5 lines' })
map('n', 'n', 'nzzzv')
map('n', 'N', 'Nzzzv')

map('v', '<C-c>', '"+y', { desc = 'Copy to clipboard' })
map('n', '<C-c>', '"+yy', { desc = 'Copy line to clipboard' })
map('v', '<C-x>', '"+d', { desc = 'Cut to clipboard' })
map('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })

map('n', '<leader>ul', function()
  vim.opt.number = not vim.opt.number:get()
end, { desc = 'Toggle line numbers' })
map('n', '<leader>uL', function()
  vim.opt.relativenumber = not vim.opt.relativenumber:get()
end, { desc = 'Toggle relative numbers' })
map('n', '<leader>uw', function()
  vim.opt.wrap = not vim.opt.wrap:get()
end, { desc = 'Toggle wrap' })
map('n', '<leader>us', function()
  vim.opt.spell = not vim.opt.spell:get()
end, { desc = 'Toggle spelling' })
map('n', '<leader>ud', function()
  vim.diagnostic.enable(not vim.diagnostic.is_enabled())
end, { desc = 'Toggle diagnostics' })
