local map = vim.keymap.set
local vscode = require('vscode')

local function call(command, opts)
  return function()
    vscode.action(command, opts)
  end
end

map('n', 'gd', call('editor.action.revealDefinition'), { desc = 'Go to definition' })
map('n', 'gD', call('editor.action.revealDeclaration'), { desc = 'Go to declaration' })
map('n', 'gi', call('editor.action.goToImplementation'), { desc = 'Go to implementation' })
map('n', 'gr', call('editor.action.goToReferences'), { desc = 'Go to references' })
map('n', 'gy', call('editor.action.goToTypeDefinition'), { desc = 'Go to type definition' })
map('n', 'K', call('editor.action.showHover'), { desc = 'Hover documentation' })
map({ 'n', 'x' }, '<leader>ca', call('editor.action.quickFix'), { desc = 'Code action' })
map('n', '<leader>rn', call('editor.action.rename'), { desc = 'Rename symbol' })
map({ 'n', 'x' }, '<leader>fm', call('editor.action.formatDocument'), { desc = 'Format document' })
map('n', '[d', call('editor.action.marker.prevInFiles'), { desc = 'Previous diagnostic' })
map('n', ']d', call('editor.action.marker.nextInFiles'), { desc = 'Next diagnostic' })
map('n', '<leader>dl', call('workbench.actions.view.problems'), { desc = 'Problems' })

map('n', '<leader><space>', call('workbench.action.quickOpen'), { desc = 'Quick open' })
map('n', '<leader>ff', call('workbench.action.quickOpen'), { desc = 'Find files' })
map('n', '<leader>fg', call('workbench.action.findInFiles'), { desc = 'Find in files' })
map('n', '<leader>fb', call('workbench.action.showAllEditorsByMostRecentlyUsed'), { desc = 'Find editors' })
map('n', '<leader>fr', call('workbench.action.openRecent'), { desc = 'Recent files' })
map('n', '<leader>fh', call('workbench.action.showCommands'), { desc = 'Command palette' })
map('n', '<leader>e', call('workbench.view.explorer'), { desc = 'Explorer' })
map('n', '<leader>E', call('workbench.files.action.showActiveFileInExplorer'), { desc = 'Reveal file' })

map('n', ']b', call('workbench.action.nextEditor'), { desc = 'Next editor' })
map('n', '[b', call('workbench.action.previousEditor'), { desc = 'Previous editor' })
map('n', '<leader>bd', call('workbench.action.closeActiveEditor'), { desc = 'Close editor' })
map('n', '<leader>bb', call('workbench.action.quickOpenPreviousRecentlyUsedEditor'), { desc = 'Previous editor' })
map('n', 'H', '0', { desc = 'Start of line' })
map('n', 'L', '$', { desc = 'End of line' })

map('n', '<C-h>', call('workbench.action.focusLeftGroup'), { desc = 'Focus left group' })
map('n', '<C-j>', '5jzz', { desc = 'Down 5 lines' })
map('n', '<C-k>', '5kzz', { desc = 'Up 5 lines' })
map('n', '<C-l>', call('workbench.action.focusRightGroup'), { desc = 'Focus right group' })
map('n', '<leader>wj', call('workbench.action.focusBelowGroup'), { desc = 'Focus lower group' })
map('n', '<leader>wk', call('workbench.action.focusAboveGroup'), { desc = 'Focus upper group' })
map('n', '<leader>wv', call('workbench.action.splitEditorRight'), { desc = 'Split right' })
map('n', '<leader>wh', call('workbench.action.splitEditorDown'), { desc = 'Split down' })
map('n', '<leader>wq', call('workbench.action.closeEditorsInGroup'), { desc = 'Close editor group' })

map('n', '<C-\\>', call('workbench.action.terminal.toggleTerminal'), { desc = 'Terminal' })
map('n', '<leader>tt', call('workbench.action.terminal.toggleTerminal'), { desc = 'Terminal' })
map('n', '<leader>gg', call('workbench.view.scm'), { desc = 'Source control' })
map('n', ']h', call('workbench.action.editor.nextChange'), { desc = 'Next change' })
map('n', '[h', call('workbench.action.editor.previousChange'), { desc = 'Previous change' })

map('n', 'gcc', call('editor.action.commentLine'), { desc = 'Comment line' })
map('x', 'gc', call('editor.action.commentLine'), { desc = 'Comment selection' })
map({ 'n', 'x' }, '<C-/>', call('editor.action.commentLine'), { desc = 'Toggle comment' })

map({ 'n', 'x' }, '<C-n>', call('editor.action.addSelectionToNextFindMatch'), { desc = 'Add next match cursor' })
map({ 'n', 'x' }, '<leader>mn', call('editor.action.addSelectionToNextFindMatch'), { desc = 'Add next match' })
map({ 'n', 'x' }, '<leader>mN', call('editor.action.addSelectionToPreviousFindMatch'), { desc = 'Add previous match' })
map({ 'n', 'x' }, '<leader>ma', call('editor.action.selectHighlights'), { desc = 'Select all matches' })
map({ 'n', 'x' }, '<leader>ms', call('editor.action.moveSelectionToNextFindMatch'), { desc = 'Skip next match' })
map({ 'n', 'x' }, '<leader>mj', call('editor.action.insertCursorBelow'), { desc = 'Add cursor below' })
map({ 'n', 'x' }, '<leader>mk', call('editor.action.insertCursorAbove'), { desc = 'Add cursor above' })
map({ 'n', 'x' }, '<C-Down>', call('editor.action.insertCursorBelow'), { desc = 'Add cursor below' })

map('n', '<leader>aa', call('workbench.action.chat.open'), { desc = 'Open AI chat' })
map('n', '<leader>aA', call('workbench.action.chat.openAgent'), { desc = 'Open AI agent' })
map({ 'n', 'x' }, '<leader>ai', call('inlineChat.start'), { desc = 'Inline AI chat' })

map('n', 'za', call('editor.toggleFold'), { desc = 'Toggle fold' })
map('n', 'zM', call('editor.foldAll'), { desc = 'Fold all' })
map('n', 'zR', call('editor.unfoldAll'), { desc = 'Unfold all' })
